In [2]:
import pandas as pd

In [3]:
country_csv = pd.read_csv('rawdata\csv\country.csv')
print(country_csv)

FileNotFoundError: [Errno 2] No such file or directory: 'rawdata\\csv\\country.csv'

In [12]:
df = pd.DataFrame(country_csv)
#copying dataframe
df1 = df.copy()
print(df1)

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

#Removing missing values

In [ ]:
#use mean for numberic columns
print(df1['Age'].dtype)
print(df1['Age'])

float64
0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

#fiiling with mean values

In [18]:
df1['Age'].fillna(df['Age'].mean(), inplace=True)

In [19]:
df1

   Country        Age   Salary Purchased
0   France  44.000000  72000.0       Yes
1    Spain  27.000000  48000.0       Yes
2      NaN  30.000000  54000.0       NaN
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

Updating df1, salary with most fequeent technique

df1['Salary'].isnull().sum()     ## gives count of null values

#below lines are to convert CSV dataframe to json format

In [24]:
df.to_json('rawdata\json\country.json', orient='records', lines=True)

In [25]:
df1['Salary'].fillna(df['Salary'].mode()[0])  ## gives most frequent value

0    72000.0
1    48000.0
2    54000.0
3    61000.0
4    48000.0
5    58000.0
6    52000.0
7    79000.0
8    83000.0
9    67000.0
Name: Salary, dtype: float64

# Using [AB_NYC_2029](rawdata/csv/AB_NYC_2019.csv)

In [26]:
df_ab_nyc = pd.read_csv('rawdata/csv/AB_NYC_2019.csv')

In [37]:
df_ab_nyc.duplicated().sum()         # to check how many duplicates are there

np.int64(11)

In [39]:
df_ab_nyc[df_ab_nyc.duplicated()]  #keep = false  # to see the duplicate rows
                                #keep = 'last'  # to keep last duplicate
                                #keep = 'first' # to keep first duplicate

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48895,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,22-06-2019,0.59,1,129
48896,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,05-10-2017,0.40,1,0
48897,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,24-06-2019,3.47,1,220
48898,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,21-07-2017,0.99,1,0
48899,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,09-06-2019,1.33,4,188
48900,5295,Beautiful 1br on Upper West Side,7702,Lena,Manhattan,Upper West Side,40.80316,-73.96545,Entire home/apt,135,5,53,22-06-2019,0.43,1,6
48901,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.76076,-73.98867,Private room,85,2,188,23-06-2019,1.50,1,39
48902,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,24-06-2019,1.34,3,314
48903,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,113,05-07-2019,0.91,1,333
48904,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,120,90,27,31-10-2018,0.22,1,0
48905,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,29-06-2019,1.20,1,46

In [ ]:
df_ab_nyc.drop_duplicates(keep='first', inplace=True)  # drop duplicates from dataframe

In [43]:
df_ab_nyc.duplicated().sum()  # to check how many duplicates are there after removing duplicates

np.int64(0)

In [44]:
df_ab_nyc.duplicated('name').sum()  # to check duplicates based on specific column

np.int64(998)

In [49]:
# now check if they really exit
df_ab_nyc[df_ab_nyc.duplicated('name')].head(10)  # to see the duplicate rows based on specific column

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
330,81739,Loft w/ Terrace @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73842,-73.95312,Private room,249,3,2,12-05-2011,0.02,28,60
339,84010,Superior @ Box House,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73813,-73.95394,Private room,179,3,13,27-06-2019,0.14,28,81
580,219818,✿✿✿ COUNTRY COTTAGE IN THE CITY✿✿✿,1138692,Keera (Jena),Manhattan,Lower East Side,40.71892,-73.98401,Entire home/apt,199,1,14,20-07-2015,0.15,2,158
661,250537,The Lenox in Harlem,1313306,Yvette,Manhattan,Harlem,40.81122,-73.94279,Entire home/apt,400,5,0,NaN,NaN,2,365
669,253471,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73641,-73.95330,Entire home/apt,199,3,24,06-11-2018,0.32,28,84
670,253475,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73794,-73.95254,Entire home/apt,199,3,59,24-06-2019,0.66,28,60
674,253800,Loft Suite @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73730,-73.95323,Entire home/apt,199,3,24,25-04-2019,0.26,28,60
675,253803,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73708,-73.95271,Entire home/apt,199,3,23,22-06-2019,0.26,28,60
676,253806,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73652,-73.95236,Entire home/apt,199,3,43,02-07-2019,0.47,28,60
677,253811,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73693,-73.95316,Entire home/apt,199,3,30,03-07-2019,0.32,28,56

In [53]:

df_ab_nyc.drop_duplicates(subset='name', keep='first', inplace=True)

In [40]:
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix','Los Angeles', 'Chicago']
rankings = [1, 2, 3, 4, 5,6,7]
scores = [9.8, 9.5, 9.2, 8.7, 8.5, 8.2, 8.1]

data = {'City': cities, 'Ranking': rankings, 'Score': scores}

df_city_ranking = pd.DataFrame(data)

Outlier

mean, variance and standard deviation (sq root of variance) impacted due to outlier 

so if you want to fill data, without outlier handling use median and mode which are lease affected