In [1]:
#Univariate non graphical analysis

In [2]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ashpi\git-projects\datascience\dataengmain\projects\basics\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ashpi\git-projects\datascience\dataengmain\projects\basics\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.9 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/11.0 MB 1.7 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/11.0 MB 1.6 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/11.0 MB 1.4 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/11.0 MB 1.4 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/11.0 MB 1.2 MB/s eta 0:00:08
   ------ --------------------------------- 1.8/11.0 MB 1.1 MB/s eta 0:00:09
   ------- -------------------------------- 2.1/11.0 MB 1.2 MB/s eta 0:00:08
   --------- ------------------------------ 2.6/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.3 MB/s eta 0:00:07
   ------------ --------------------------- 3.4/11.0 MB 930.5 kB/s eta 0:00:09
   ------------ --------------------------- 3.4/11.0 MB 930.5 kB/s eta 0:00:09
   ------------ --------------------------- 3.4/11.0 MB 930.5 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/11.0 MB 849.6 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/11.0 MB 849.6 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/11.0 MB 849.6 kB/s eta 0:00:09
   -------------- ------------------------- 3.9/11.0 MB 786.0 kB/s eta 0:00:09
   --------------- ------------------------ 4.2/11.0 MB 807.1 kB/s eta 0:00:09
   ---------------- ----------------------- 4.5/11.0 MB 818.2 kB/s eta 0:00:08
   ----------------- ---------------------- 4.7/11.0 MB 843.1 kB/s eta 0:00:08
   ------------------- -------------------- 5.2/11.0 MB 893.6 kB/s eta 0:00:07
   -------------------- ------------------- 5.5/11.0 MB 912.1 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 928.3 kB/s eta 0:00:06
   --------------------- ------------------ 6.0/11.0 MB 941.8 kB/s eta 0:00:06
   ---------------------- ----------------- 6.3/11.0 MB 950.6 kB/s eta 0:00:05
   ----------------------- ---------------- 6.6/11.0 MB 958.9 kB/s eta 0:00:05
   ----------------------- ---------------- 6.6/11.0 MB 958.9 kB/s eta 0:00:05
   ------------------------- -------------- 7.1/11.0 MB 961.9 kB/s eta 0:00:05
   -------------------------- ------------- 7.3/11.0 MB 972.6 kB/s eta 0:00:04
   --------------------------- ------------ 7.6/11.0 MB 983.6 kB/s eta 0:00:04
   ----------------------------- ---------- 8.1/11.0 MB 1.0 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.0 MB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.0 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 1.2 MB/s  0:00:09
Downloading numpy-2.3.3-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 1.3 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.8 MB 1.5 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/12.8 MB 1.6 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.8 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.8 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.8 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/12.8 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:08
   --------- ------------------------------ 3.1/12.8 MB 1.4 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.8 MB 1.4 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.8 MB 1.5 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.8 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 4.7/12.8 MB 1.5 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/12.8 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.8 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.8 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.8 MB 1.5 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.8 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 5.8/12.8 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.3/12.8 MB 1.3 MB/s eta 0:00:05
   -------------------- ------------------- 6.6/12.8 MB 1.4 MB/s eta 0:00:05
   ---------------------- ----------------- 7.1/12.8 MB 1.4 MB/s eta 0:00:05
   ----------------------- ---------------- 7.6/12.8 MB 1.4 MB/s eta 0:00:04
   ------------------------ --------------- 7.9/12.8 MB 1.4 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.8 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 8.9/12.8 MB 1.5 MB/s eta 0:00:03
   ----------------------------- ---------- 9.4/12.8 MB 1.5 MB/s eta 0:00:03
   ------------------------------ --------- 9.7/12.8 MB 1.5 MB/s eta 0:00:03
   ------------------------------- -------- 10.2/12.8 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 10.5/12.8 MB 1.6 MB/s eta 0:00:02
   ---------------------------------- ----- 11.0/12.8 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.8 MB 1.6 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 1.6 MB/s  0:00:08
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]

In [3]:
import pandas as pd

In [4]:
pd.read_csv(r'C:\Users\ashpi\git-projects\dataScience\DataEngMain\projects\basics\rawdata\csv\AB_NYC_2019.csv')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48901,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.76076,-73.98867,Private room,85,2,188,23-06-2019,1.50,1,39
48902,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,24-06-2019,1.34,3,314
48903,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,113,05-07-2019,0.91,1,333
48904,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,120,90,27,31-10-2018,0.22,1,0
48905,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,29-06-2019,1.20,1,46

In [5]:
try:
    data = pd.read_csv(r'C:\Users\ashpi\git-projects\dataScience\DataEngMain\projects\basics\rawdata\csv\AB_NYC_2019.csv')
except FileNotFoundError:
    print("File not found. Please check the file path.")
    print("Tip: To use a relative path, place 'AB_NYC_2019.csv' in your working directory and use:")
    print("    pd.read_csv('AB_NYC_2019.csv')")
except OSError as e:
    print(f"OS error check file path: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

In [6]:
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48906 entries, 0 to 48905
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48906 non-null  int64
 1   name                            48890 non-null  object
 2   host_id                         48906 non-null  int64
 3   host_name                       48885 non-null  object
 4   neighbourhood_group             48906 non-null  object
 5   neighbourhood                   48906 non-null  object
 6   latitude                        48906 non-null  float64
 7   longitude                       48906 non-null  float64
 8   room_type                       48906 non-null  object
 9   price                           48906 non-null  int64
 10  minimum_nights                  48906 non-null  int64
 11  number_of_reviews               48906 non-null  int64
 12  last_review                     38854 non-null  object
 13  reviews_per_month               38854 non-null  float64
 14  calculated_host_listings_count  48906 non-null  int64
 15  availability_365                48906 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [7]:
df.describe()      # for numerical columns, df.describe(include='all') for all columns

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.890600e+04,4.890600e+04,48906.000000,48906.000000,48906.000000,48906.000000,48906.000000,38854.000000,48906.000000,48906.000000
mean,1.901287e+07,6.760480e+07,40.728952,-73.952175,152.711324,7.031612,23.300454,1.373151,7.142702,112.782031
std,1.098557e+07,7.860866e+07,0.054529,0.046154,240.128713,20.512489,44.607175,1.680270,32.948926,131.620370
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.464662e+06,7.809567e+06,40.690100,-73.983080,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967545e+07,3.078463e+07,40.723080,-73.955685,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915085e+07,1.074344e+08,40.763120,-73.936283,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [8]:
df.describe(include='all')  # for all columns

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
count,4.890600e+04,48890,4.890600e+04,48885,48906,48906,48906.000000,48906.000000,48906,48906.000000,48906.000000,48906.000000,38854,38854.000000,48906.000000,48906.000000
unique,NaN,47896,NaN,11452,5,221,NaN,NaN,3,NaN,NaN,NaN,1764,NaN,NaN,NaN
top,NaN,Hillside Hotel,NaN,Michael,Manhattan,Williamsburg,NaN,NaN,Entire home/apt,NaN,NaN,NaN,23-06-2019,NaN,NaN,NaN
freq,NaN,18,NaN,417,21669,3921,NaN,NaN,25414,NaN,NaN,NaN,1414,NaN,NaN,NaN
mean,1.901287e+07,NaN,6.760480e+07,NaN,NaN,NaN,40.728952,-73.952175,NaN,152.711324,7.031612,23.300454,NaN,1.373151,7.142702,112.782031
std,1.098557e+07,NaN,7.860866e+07,NaN,NaN,NaN,0.054529,0.046154,NaN,240.128713,20.512489,44.607175,NaN,1.680270,32.948926,131.620370
min,2.539000e+03,NaN,2.438000e+03,NaN,NaN,NaN,40.499790,-74.244420,NaN,0.000000,1.000000,0.000000,NaN,0.010000,1.000000,0.000000
25%,9.464662e+06,NaN,7.809567e+06,NaN,NaN,NaN,40.690100,-73.983080,NaN,69.000000,1.000000,1.000000,NaN,0.190000,1.000000,0.000000
50%,1.967545e+07,NaN,3.078463e+07,NaN,NaN,NaN,40.723080,-73.955685,NaN,106.000000,3.000000,5.000000,NaN,0.720000,1.000000,45.000000
75%,2.915085e+07,NaN,1.074344e+08,NaN,NaN,NaN,40.763120,-73.936283,NaN,175.000000,5.000000,24.000000,NaN,2.020000,2.000000,227.000000
max,3.648724e+07,NaN,2.743213e+08,NaN,NaN,NaN,40.913060,-73.712990,NaN,10000.000000,1250.000000,629.000000,NaN,58.500000,327.000000,365.000000

In [9]:
df.head()     # First 5 rows

df.tail()     # Last 5 rows

df.sample(5)  # Random sample of 5 rows

df.columns    # to get all column names

df.shape      # to get now of rowss and columns

(48906, 16)

#first get some insight of the data before doing the analysis
#use above methods to get insight

In [10]:
df['room_type']

0           Private room
1        Entire home/apt
2           Private room
3        Entire home/apt
4        Entire home/apt
              ...
48901       Private room
48902       Private room
48903       Private room
48904    Entire home/apt
48905    Entire home/apt
Name: room_type, Length: 48906, dtype: object

In [11]:
df['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

In [12]:
df['room_type'].value_counts()

room_type
Entire home/apt    25414
Private room       22332
Shared room         1160
Name: count, dtype: int64

In [13]:
room_counts = df['room_type'].value_counts(normalize=True)  
# assign result to another variable

room_counts[0]
# first occurance

room_counts.iloc[2]
# use this method now, first one is depriciated

C:\Users\ashpi\AppData\Local\Temp\ipykernel_15032\2368504861.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  room_counts[0]

np.float64(0.02371897108739214)

In [14]:
for r_cnt in room_counts:
    print(r_cnt)

0.5196499407025723
0.45663108821003556
0.02371897108739214

categorical column neighbourhood_group analysis

In [15]:
df["neighbourhood_group"].value_counts()

neighbourhood_group
Manhattan        21669
Brooklyn         20107
Queens            5666
Bronx             1091
Staten Island      373
Name: count, dtype: int64

In [16]:
for i in df["neighbourhood_group"].value_counts():
    print(i)

21669
20107
5666
1091
373

In [17]:
df["neighbourhood_group"].value_counts(normalize=True)   # will tell you percentage

neighbourhood_group
Manhattan        0.443074
Brooklyn         0.411136
Queens           0.115855
Bronx            0.022308
Staten Island    0.007627
Name: proportion, dtype: float64

In [18]:
for i in  df["neighbourhood_group"].value_counts(normalize=True).items():  # iterate over tuples, 
    print(i)

('Manhattan', 0.44307446939025885)
('Brooklyn', 0.41113564797775326)
('Queens', 0.11585490532858954)
('Bronx', 0.022308101255469677)
('Staten Island', 0.00762687604792868)

In [19]:
list(df["neighbourhood_group"].value_counts(normalize=True).items())  # if you want to convert it to list of tuples

[('Manhattan', 0.44307446939025885),
 ('Brooklyn', 0.41113564797775326),
 ('Queens', 0.11585490532858954),
 ('Bronx', 0.022308101255469677),
 ('Staten Island', 0.00762687604792868)]

In [20]:
for i in df["neighbourhood_group"].value_counts(normalize=True):
    print(i)

0.44307446939025885
0.41113564797775326
0.11585490532858954
0.022308101255469677
0.00762687604792868

In [21]:
 neighbourhood_group= df['neighbourhood_group'].drop_duplicates() 
 df['neighbourhood_group'].drop_duplicates()

0           Brooklyn
1          Manhattan
46            Queens
169    Staten Island
171            Bronx
Name: neighbourhood_group, dtype: object

In [22]:
neighbourhood_group[0:3]

0      Brooklyn
1     Manhattan
46       Queens
Name: neighbourhood_group, dtype: object

Analyzing Numerical Data Price

In [23]:
df['price'].describe()

df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.890600e+04,4.890600e+04,48906.000000,48906.000000,48906.000000,48906.000000,48906.000000,38854.000000,48906.000000,48906.000000
mean,1.901287e+07,6.760480e+07,40.728952,-73.952175,152.711324,7.031612,23.300454,1.373151,7.142702,112.782031
std,1.098557e+07,7.860866e+07,0.054529,0.046154,240.128713,20.512489,44.607175,1.680270,32.948926,131.620370
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.464662e+06,7.809567e+06,40.690100,-73.983080,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967545e+07,3.078463e+07,40.723080,-73.955685,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915085e+07,1.074344e+08,40.763120,-73.936283,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000